<?php

use Faker\Generator as Faker;

$factory->define(\App\Student::class, function (Faker $faker) {
    return [
        'legal_id' => $faker->isbn10,
        'passport_id' => $faker->isbn10,
        'photo' => $faker->imageUrl(20, 20),
        'program_group' => $faker->numberBetween(1, 50),
        'name' => $faker->firstName,
        'surname' => $faker->lastName,
        'main_email' => $faker->email,
        'mobile_number' => $faker->phoneNumber,
        'home_number' => $faker->phoneNumber,
        'birth_date' => $faker->date('Y-m-d', '1994-01-01'),
        'other_city_of_birth' => '',
        'home_address_1' => $faker->address,
        'home_address_2' => '',
        'zip_code' => $faker->postcode,
        'map_lat' => $faker->latitude,
        'map_lon' => $faker->longitude,
        'facebook_url' => 'http://www.facebook.com/',
        'linkedin_url' => 'http://www.linkedin.com/',
        'twitter_url' => 'http://www.twitter.com/',
        'personal_url' => 'http://www.personal.com',
        'current_job_experience_time' => $faker->numberBetween(1, 15),
        'current_managerial_experience_time' => $faker->numberBetween(0, 10),
        'planning_to_open_company' => $faker->numberBetween(0, 1),
        'main_obstacle_create_company' => $faker->numberBetween(1, 4),
        'had_promotion_after_espae' => $faker->numberBetween(0, 1),
        'had_incomes_increase' => $faker->numberBetween(0, 1),
        'had_responsabilities_increase' => $faker->numberBetween(0, 1),
        'life_plan_after_espae' => $faker->numberBetween(1, 4),
        'reality_vs_expectative' => $faker->numberBetween(1, 4),
        'belong_level_espae' => $faker->numberBetween(1, 5),
        'work_knowledge_value' => $faker->numberBetween(1, 5),
        'life_knowledge_value' => $faker->numberBetween(1, 5),
        'satisfaction_level_espae' => $faker->numberBetween(1, 5),
        'would_recomend_espae' => $faker->numberBetween(1, 5),
        'graduate_services_wish' => $faker->numberBetween(1, 4),
        'satisfaction_level_graduate_relation' => $faker->numberBetween(1, 5),
        'other_programs_espae_in_future' => $faker->numberBetween(1, 4),
        'country_id_birth' => $faker->numberBetween(1, 10),
        'country_id_residence' => $faker->numberBetween(1, 10),
        'ec_city_id_residence' => $faker->numberBetween(1, 10),
        'civil_status_id' => $faker->numberBetween(1, 5),
        'blood_type_id' => $faker->numberBetween(1, 5),
        'gender_id' => $faker->numberBetween(1, 5),
        'ethnic_group_id' => $faker->numberBetween(1, 5),
        'job_status_id' => $faker->numberBetween(1, 5),
        'program_id' => $faker->numberBetween(1, 5),
    ];
});
